sudo: required
services:
    - docker
before_installed: 
    - docker build -t 7333584/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true 7333584/docker-react npm run test 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker" 
    env: "Docker-env" 
    bucket_name: "elasticbeanstalk-us-east-2-065545901698"
    bucket_path: "docker"
    aws_access_key: $AWS_ACCESS_KEY
    aws_secret_key:
        secure: "$AWS_SECRET_KEY"
    on:
        branch: master

